---
- name: Update DNF Package repository cache
  dnf:
    update_cache: True
  become: true
  when: inventory_hostname == 'sitafs-mysql8'

- name: Install mysql
  dnf:
    name: "mysql-common,mysql,mysql-server,python3-PyMySQL"
    state: present
  become: true
  when: inventory_hostname == 'sitafs-mysql8'
        
- name: Stop mysql-server
  service: name=mysqld state=stopped
  become: true
  when: inventory_hostname == 'sitafs-mysql8'

- name: create config directory  MySQL
  shell: mkdir /etc/mysql/conf.d
  become: True
  when: inventory_hostname == 'sitafs-mysql8'

- name: Configure MySQL 
  copy: 
    src: mysqld_0.cnf 
    dest: /etc/mysql/conf.d/mysqld_0.cnf
  become: true
  when: inventory_hostname == 'sitafs-mysql8'

- name: Start MySQL
  service: name=mysqld state=started enabled=true
  become: true
  when: inventory_hostname == 'sitafs-mysql8'

- name: Wait for MySQL to start
  wait_for: port=3306 search_regex=mysql
  when: inventory_hostname == 'sitafs-mysql8'

- name: Set MySQL root Password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: '{{ database_root_password }}'
    state: present
  when: inventory_hostname == 'sitafs-mysql8'



- name: Check if mysql root password is enabled
  mysql_variables: login_user=root login_password="{{ database_root_password }}" variable=timestamp
  register: chktime
  ignore_errors: True
  when: inventory_hostname == 'sitafs-mysql8'


- name: Set MySQL root Password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: '{{ database_root_password }}'
    name: 'sas_java'
    password: 'password'
    state: present
  when: inventory_hostname == 'sitafs-mysql8'  