---
## YAML based inventory, see:
## https://docs.ansible.com/ansible/latest/plugins/inventory/yaml.html
#
## Simple example using defaults to spin up 3 CentOS guests
## This is on multiple KVM hosts, see kvmhost.yml
simple:
  hosts:
    sitafs-sas:
    sitafs-mysql8:
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
