---
# Only run on KVM host
- name: Stop networks
  virt_net:
    state: inactive
    name: "{{ item.name }}"
  with_items: "{{ virt_infra_host_networks.absent }}"
  when:
    - inventory_hostname in groups['kvmhost']
    - item.type is not defined or (item.type is defined and item.type != "bridge")
    - item.name is defined
  become: true

- name: Undefine networks
  virt_net:
    command: undefine
    name: "{{ item.name }}"
    xml: '{{ lookup("template", "templates/virt-network.j2") }}'
  with_items: "{{ virt_infra_host_networks.absent }}"
  when:
    - inventory_hostname in groups['kvmhost']
    - item.type is not defined or (item.type is defined and item.type != "bridge")
    - item.name is defined
  become: true
