---
- name: Remove virtual BMC
  shell: "set -o pipefail && {{ hostvars[kvmhost].result_vbmc_path.stdout }} delete {{ inventory_hostname }}"
  args:
    executable: /bin/bash
  become: true
  register: result_vbmc_remove
  retries: 10
  delay: 2
  until: result_vbmc_remove is succeeded
  when:
    - inventory_hostname not in groups['kvmhost']
    - virt_infra_state | default(virt_infra_state) == "undefined"
    - virt_infra_vbmc_port is defined and virt_infra_vbmc_port
    - hostvars[kvmhost].virt_infra_vbmc is defined and hostvars[kvmhost].virt_infra_vbmc or virt_infra_vbmc
    - hostvars[kvmhost].result_vbmc_list is defined and inventory_hostname in hostvars[kvmhost].result_vbmc_list.stdout
  delegate_to: "{{ kvmhost }}"
  notify:
    - restart virtual bmc

- meta: flush_handlers
